### ISSUE TITLE
[Bug] Split Dirvish's windows show the same path

### ISSUE THREAD

**Issue by Patryk27** [alexluigit/dirvish#109]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

After a Dirvish's window is split, navigating inside that second instance causes the first instance's path (the one displayed at the top) to be updated (even though the viewport remains untouched).

### Steps to reproduce

- Open Dirvish,
- Split the window (e.g. `(+evil/window-vsplit-and-follow)`),
- Inside that second window navigate to some other directory,
- See that the first instance's path (at the top of the window) has changed, even though the viewport (i.e. the actually previewed directory) has not.

### Expected behavior

My guess would be that after splitting, both windows should be totally separate Dirvish instances - and while that works for the most part (i.e. navigating inside the second window won't affect the first window's currently-opened directory), it looks like the path displayed at the top remains "shared".

### OS

Linux

### Emacs Version

gccemacs-29

### Emacs Configurations

Doom Emacs

### Anything else

Of course, thanks for Dirvish! ❤️

**Comment by alexluigit** [comment]
Thanks for reporting this. I wouldn't say it's a bug since the newly split-off window displays the old buffer, therefore, the dirvish instance is reused too, I'm aware that it's annoying though.  There are several ways to solve this issue:
1. provide new commands such as dirvish-split-right/below then remap +evil/window-vsplit-and-follow and friends 
2. use dired-other-window/dired-find-file-other-window
3. advice split-window function (might be hacky)

I'm not sure. What do you think? Do you have better solutions to this?

**Comment by Patryk27** [comment]
My elisp-fu is so-so, but advicing `split-window` feels like a neat solution.

I'm using Doom Emacs, so at the very list I think the first approach will not cut it, since splitting windows is bound to the global, leader-based keymap (e.g. `SPC w v`), and Doom doesn't allow to overwrite those per major-mode, IIRC.
