### ISSUE TITLE
pre-select + auto-expand to current file when invoking dirvish-side

### ISSUE THREAD

**Issue by jdtsmith** [alexluigit/dirvish#113]
(As an aside, please take the deluge of feature requests as a sign of positive _delight_ with dirvish... despite many attempts over the years, dired never clicked with me; dirvish just does.  Amazing.)

**Overview**

One of the great things about `dired-jump`, vs. plain `ls` in a shell, is you can see at a glance _from where you jumped_, since the current file gets selected.  On the other hand, `dirvish-side` is a great way to get a high-level project overview in a minimum of space, but it lacks this feature.  

**Describe the solution you'd like**

It would be wonderful if `dirvish-side`, like `dired-jump`, _pre-selected the file_ from which it was invoked.  If that file is in some nested directory in a project, and collapse is enabled, dirvish can then _auto-expand_ the necessary directory hierarchy to reveal the file.  Then you'd have the best of both worlds: local situational awareness of the file in question in its directory, and high-level browsable overview of the entire project.  

**Describe alternatives you've considered**

In principle `dired-goto-file` (`j`) would work for this, but it 1) is repeated effort when launching dirvish-side and 2) ignores files selected at lower levels of the file hierarchy below the current dir (see below).  

**Additional context**
A sub-feature-request would be for `dired-goto-file` to some nested file/subdir of the local dir to auto-expand as well.  Probably these would share implementation so thought I'd mention here.  This is relevant for all dirvish window flavors.  

One idea would be a `dirvish-auto-expand-directories` custom config, `nil` by default, which can be set to the maximum number of directories to auto-expand to reveal a file.

Thanks^100 for dirvish.

**Comment by alexluigit** [comment]
> As an aside, please take the deluge of feature requests as a sign of positive delight with dirvish... 

Although dirvish has a relatively small core, the extensions it offers actually make it a versatile thing.  Since dirvish have parity features as in dired/dired-hacks/ranger.el/neotree and so much more, it's not an unusual thing to me when a heavy user of dirvish has many feature requests.  So no worries, I don't mind it at all :)

> It would be wonderful if dirvish-side, like dired-jump, pre-selected the file from which it was invoked. If that file is in some nested directory in a project, and collapse is enabled, dirvish can then auto-expand the necessary directory hierarchy to reveal the file.  
... One idea would be a dirvish-auto-expand-directories custom config, nil by default, which can be set to the maximum number of directories to auto-expand to reveal a file.

This is on the roadmap, I planned to implement this as soon as the _dirvish-subtree.el_ is stable enough.

> A sub-feature-request would be for dired-goto-file to some nested file/subdir of the local dir to auto-expand as well. 

I've thought about this too.  We can provide a new command `dirvish-goto-file` for this.  Despite `dired-goto-file` is an user command, it is also being used in dired internally, so overriding this might not be a good idea.

**Comment by jdtsmith** [comment]
Great, happy to test out auto-expand when you have something to try.  Feel free to close unless you need the reminder.

**Comment by alexluigit** [comment]
Now we have it enabled by default. Try it out!

**Comment by jdtsmith** [comment]
Thanks.  Works great!
