### ISSUE TITLE
turning off exa colors

### ISSUE THREAD

**Issue by haluk** [alexluigit/dirvish#13]
Hi,

How do you turn off `exa` colors. I'm using Doom Emacs and timestamp color is not prominent. I override `dirvish-preview-directory-exa-dispatcher` function in my `config.el`, but didn't work. Blue color tone doesn't look good to me.

![image](https://user-images.githubusercontent.com/183110/155355759-e15862c9-5df3-4b3e-9c72-ae910c933c43.png)

**Comment by alexluigit** [comment]
Hi Haluk. 
You don't have to override any function.

If you want to use built-in Dired as your directory previewer, just do:
```emacs-lisp 
(setq dirvish-preview-dispatchers (remove 'directory-exa dirvish-preview-dispatchers))
```

If you want to keep using `exa` to preview directories, you can customize faces in `ansi-colors.el` like:
```emacs-lisp
(set-face-attribute 'ansi-color-blue nil :foreground "#FFFFFF") 
```

The latter approach is recommended since `exa` command can be executed asynchronously (move up and down feels much more responsive).
