### ISSUE TITLE
[Bug] Moving cursor in a split window affects the other window

### ISSUE THREAD

**Issue by Patryk27** [alexluigit/dirvish#145]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

It's actually similar to https://github.com/alexluigit/dirvish/issues/109, but in this case after splitting the window, moving cursor in the other window affects the first window.

### Steps to reproduce

- Open Dirvish,
- Split the window (e.g. `(+evil/window-vsplit-and-follow)`),
- Move cursor (e.g. up/down),
- See that it affects both windows instead of just the one you're focused in.

### Expected behavior

I think that only the window one is focused in should get affected; this has worked correctly before (e.g. on `5beeff36ab0c539f9d3df8e4f5a933f4d3167f30`), so I guess some refactoring or something must've broken this behavior (unless it's intended, but it feels kinda unintuitive and weird to me).

### OS

Linux

### Emacs Version

29

### Emacs Configurations

Doom Emacs

**Comment by alexluigit** [comment]
It is actually the same behavior as in Dired.  After you split a window side by side, they are displaying the same buffer, the only difference is dirvish also update the line highlighting.  I remove the hacks to create new session automatically because it caused a lot of interaction issues (https://github.com/alexluigit/dirvish/issues/136).

You can define a custom command to ensure a new dirvish session upon window split, or advice the window splitting command of your choice.

```emacs-lisp
(defun dirvish-vsplit ()
  "Split window vertically and ensure a new dirvish session."
  (interactive)
  (let ((dir default-directory)
        (dirvish-reuse-session t))
    (+evil/window-vsplit-and-follow)
    (dirvish-quit)
    (let (dirvish-reuse-session) (dired dir))))
```
