### ISSUE TITLE
how to enable `dired-omit-mode` in `dirvish-subtree-toggle`

### ISSUE THREAD

**Issue by anupam312nwd** [alexluigit/dirvish#160]
Hi, I have the following setting ```:hook (dired-mode . dired-omit-mode)``` under `dirvish` package. 
I want to enable it while using `dirvish-subtree-toggle` too, such that current folder `.` and parent folder `..` do not appear during `dirvish-subtree-toggle`.
I tried looking into `dirvish-*` variables but could not get it resolved.

Here is my config:
```
(use-package! dirvish
  :defer t
  :init (after! dired (dirvish-override-dired-mode))
  :hook (dired-mode . dired-omit-mode)
  :config
  (setq dirvish-cache-dir (concat doom-cache-dir "dirvish/")
        dirvish-hide-details nil
        dirvish-attributes '(all-the-icons file-size)
        )
  (remove-hook 'dired-mode-hook 'all-the-icons-dired-mode))
```

Thanks.

**Comment by alexluigit** [comment]
Have you ever tried to tweak `dirvish-subtree-listing-switches`? Maybe adding `almost-all` to this option?

Personally I would suggest adding `--almost-all` in your `dired-listing-switches` so that `.` and `..` won't appear anywhere since `.` doesn't do anything and the functionality of `..` can be replaced by `dired-up-directory`.

**Comment by liuyinz** [comment]
In https://github.com/alexluigit/dirvish/pull/268, I fix the issue. @anupam312nwd
