### ISSUE TITLE
Copying files over TRAMP

### ISSUE THREAD

**Issue by jumper047** [alexluigit/dirvish#37]
Dirvish's file copying mechanics sadly don't work over tramp, while dired default copying/moving works fine.

**Comment by alexluigit** [comment]
I am planning to bring in `rsync` to deal with copy/paste between remote hosts. But it might takes me some time to implement this, because the `dirvish-yank` library needs some refurbishing. See https://github.com/alexluigit/dirvish/issues/34#issuecomment-1114131136 and https://github.com/alexluigit/dirvish/issues/26

**Comment by alexluigit** [comment]
Please checkout the latest commit, I don't have time to test it for now, so any feedback/bug report is appreciated. Cheers.

**Comment by noctuid** [comment]
I could not get it to work over ssh.  For `dirvish-yank` or `dirvish-move` with just TRAMP/ssh, nothing happens.  If I use both sudo/ssh with TRAMP, I get an error:

`Error running timer: 'dirvish-yank--status-update': (remote-file-error "Forbidden reentrant call of Tramp"`

**Comment by alexluigit** [comment]
I have ssh config looks like this.
```ssh-config
TCPKeepAlive yes
AddKeysToAgent yes
AddressFamily inet

Host alex
  HostName myhost.name
  User root
  Port port_number
  IdentityFile ~/.config/ssh/id_rsa
```
This is how `dirvish-yank` command work on my machine (I open the connection using `find-file`).

https://user-images.githubusercontent.com/16313743/167150975-5e618ac7-5fd8-43cf-a419-c5b08be96d59.mp4

remote to local / local to remote works in a similar way (just without overwrite prompt because rsync handles that)

I haven't tested copying files from remote-A to remote-B, not sure if it works.

Does the file preview works over TRAMP? Do you have any special config for TRAMP or ssh?

**Comment by alexluigit** [comment]
fa5f3475eff20a67ce4c4446b3c2d74cd6f1f92c makes the "\*Dirvish-yank\*" buffer (a hidden buffer, prefix a space to access it) logs the recent 10 yank process. Anything interesting in this buffer?

**Comment by jumper047** [comment]
Just tested with kubernetes pod (via kubel), no luck - copying not working.
Got this error:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  dirvish-yank--status-update()
  apply(dirvish-yank--status-update nil)
  timer-event-handler([t 25206 16955 449155 0.1 dirvish-yank--status-update nil nil 878000 nil])
```

**Comment by alexluigit** [comment]
> Also no Dirvish-yank buffer appears

This buffer won't popup automatically.

```emacs-lisp
(switch-to-buffer dirvish-yank--buffer)
```

**Comment by alexluigit** [comment]
I have no idea why `dirvish-yank--status-update` would raise an error. But since it has nothing to do with the file I/O, for debugging purpose, it's OK to temporarily disable it, just eval this to redefine the `dirvish-yank--execute` function:

```emacs-lisp
(defun dirvish-yank--execute (cmd)
  "Run yank CMD in subprocesses."
  (let ((process-connection-type nil)
        (procname (format "*Dirvish-yank @ %s*" (current-time-string))))
    (start-process-shell-command procname dirvish-yank--buffer cmd)))
```

Then try `dirvish-yank` again and see what's in `dirvish-yank--buffer`

```emacs-lisp
(switch-to-buffer dirvish-yank--buffer)
```

**Comment by noctuid** [comment]
For me, it is some permissions issue.  This shows up instead of preview and in the yank buffer logs.  Normal dired operations work correctly.  Is some extra setup required for dirvish?  I do not have ssh-askpass installed on either machine.  Should it be necessary?

```
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Permission denied, please try again.
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Permission denied, please try again.
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
<username>@192.168.2.2: Permission denied (publickey,password)
```

I am connecting to a local computer over ethernet with a password only.  I have no ssh or TRAMP configuration.

For whatever reason, the username shown at the end is not the one I used to connect to the remote host with; it is my local username (not sure if that is a problem).

**Comment by alexluigit** [comment]
This is the excerpt from _dirvish.el_ that in charge of the file preview on remote host.

```emacs-lisp
(dirvish-define-preview remote (file)
  "Preview files with `ls' or `cat' for remote files."
  (when-let ((local (file-remote-p file 'localname)))
    `(shell . ("ssh" ,(file-remote-p file 'host) "test" "-d" ,local
               "&&" "ls" "-Alh" "--group-directories-first" ,local
               "||" "cat" ,local))))
```

What it does is basically composes and issues a shell command looks like this:

```shell
ssh foo test -d /path/to/file && ls -Alh --group-directories-first /path/to/file || cat /path/to/file
```
The `test -d ... ls ... cat ...` part in the command is a normal shell command, nothing special.
The `ssh foo` here makes the command being run remotely instead of locally, where the host name "foo" should be defined in the ~/.ssh/config like 

```ssh-config
# other configs for performance
# ...
Host foo
  HostName foo.name # in the form of "google.com"
  User root # the login username
  Port port_number # usually 22
  IdentityFile /path/to/identity_file
```

If I run this command in the terminal, I'll get the text content or directory listing for that file, which is the same content being displayed as preview inside of dirvish. 

In other words, if this shell command cannot work properly, the preview cannot work either. The same principle applies to `dirvish-yank` and friends within the same remote host 
 (hostA-hostB are handled by `rsync`, no `ssh` involved), because they do similar things except using `cp` or `mv` and the like to achieve different tasks.

> I do not have ssh-askpass installed on either machine. Should it be necessary?

All I installed is the [openSSH](https://wiki.archlinux.org/title/OpenSSH) on Arch, nothing else. Other than that, I've copied the pubkey to the "foo" using `ssh-add` so that I don't have to enter the password. FWIW I also used `ssh-agent` to start my X environment, but I'm not sure if that is relevant to this issue.

I did not even tried to use TRAMP for file preview and copy/paste because it seems that there are endless amount of synchronous chitchat on just opening a file. Maybe I'm wrong about that.

Will the ssh config above issue this issue for you? If not, what's the error message in the preview buffer?
I guess this problem can be solved by composing the shell command in a different way or something, but I have no idea on how to do that since I don't have the environment as you described. A workable shell command (without prompting for password) would be very helpful for this issue.

**Comment by noctuid** [comment]
> Will the ssh config above solves this issue for you? If not, what's the error message in the preview buffer? ... A workable shell command (without prompting for password) would be very helpful for this issue.

I will try next time I get the chance.  TRAMP does not require any ssh config file though.  Shouldn't it be possible to get all this information from Emacs (except maybe the password) and then run `ssh -l <user> <host> ...`?

If possible, I think it would be better to do things through TRAMP though.  It can prompt for the password itself.  More importantly, it supports a lot more than just ssh e.g. sudo, docker, and combining different protocols.  For example, I used to occasionally pipe ssh to sudo to docker to work inside docker containers on a remote machine (though in this case I was using eshell mostly rather than needing dired).  Since dirvish is not using TRAMP, that probably explains why it did not work with a kubernetes pod for @jumper047 (not sure if you can acually ssh into a kubernetes pod or if it works like it does for docker in docker-tramp.el with a separate protocol).

I haven't looked at how TRAMP and dired work together by default, so maybe it is just not easily possible to have async file movement this way.  If the current implementation is the only way to do it, the documentation should mention it only supports ssh and requires ssh configuration to avoid asking for a password.  I will try to get this working sometime next week.  Thanks for the explanation.

**Comment by alexluigit** [comment]
> Shouldn't it be possible to get all this information from Emacs (except maybe the password) and then run ssh -l <user> <host> ...?

This would be a promising solution, but I'm sure if the sub-process have access to the password that is captured by TRAMP, which was the reason I didn't tried this approach. I'll give it a try. 

> If possible, I think it would be better to do things through TRAMP though.

It would be great if we can do these through TRAMP, that's also the spirit of dirvish. I'll see if I can bypass the synchronous part of TRAMP and come with up a better solution than the current ssh one. I've never been able to read through the source code of TRAMP, because I was always intimidated by the intensive usage of regex there :confused: . But I'll try my best. 

> If the current implementation is the only way to do it, the documentation should mention it

Definitely. I'll improve the doc on this once I (hopefully) figure out the TRAMP stuff. Thanks for your advice and feedback.

**Comment by noctuid** [comment]
> It would be great if we can do these through TRAMP, that's also the spirit of dirvish. I'll see if I can bypass the synchronous part of TRAMP and come with up a better solution than the current ssh one. I've never been able to read through the source code of TRAMP, because I was always intimidated by the intensive usage of regex there confused . But I'll try my best.

`tramp-handle-shell-command` supports running async shell commands, though I do not not if that is the correct thing to use for this functionality.  I've seen discussions about wanting async file copying with TRAMP without any solutions, so it may be that it is very hard to do with TRAMP.

**Comment by alexluigit** [comment]
> `tramp-handle-shell-command` supports running async shell commands, though I do not not if that is the correct thing to use for this functionality.

Yes, it probably is the right way to go, I have tried to implement the preview part with this function yesterday and it's working pretty well (although some TRAMP config are required to ensure a usable performance). Since we can use it for preview then I guess we can use it for copy/paste as well.  The tricky thing I'm facing now is how to keep as more as features that work locally also works on TRAMP (hopefully we can remove the `dirvish-enable-features-on-remote` option). Thanks for suggestion anyway, stay tuned!

**Comment by alexluigit** [comment]
> Is it actually impossible, or is the performance just worse? 

Sorry for the confusion. I'm not a TRAMP expert so my understanding can be wrong, but here's what I found:
`tramp-handle-shell-command` can handle a shell command that includes "&" no matter the `direct-async-process` property is present or not within the connection. But before handling every shell command, we have to go through a synchronous connection phase (the "overhead" described in that page, which takes very long time for a remote connection) _unless_ the connection has the `direct-async-process` property set to t.  In other words, it doesn't matter the command itself is handled synchronously or asynchronously because that is not the bottleneck. The synchronous nature of this connection initialization makes it "impossible" for us to implement an usable file preview and etc.

> Can't you still use asynchronous processes without direct-async-process, or is the performance too bad?

As I described above, if the connection does not come with the `direct-async-process` property, every command takes ~ 1-2s (blocking) to establish the connection synchronously, then get spawned. Basically unusable.

> What about over a multi-hop connection? Will they block or just not work?

```
Using direct asynchronous processes in TRAMP is not possible, 
if the remote host is connected via multiple hops. 
In this case, TRAMP falls back to its classical implementation.
```
If I understood this correctly, I think it means "multi-hop connection = always synchronous"
So I disabled these features on synchronous connections (including mulit-hop ones), it won't block. You'll see "File preview is not supported in current TRAMP connection" in the preview window on this kind of connection.

> So file copy/move is still using rsync directly.

Yes, but it's only used when source files and target are located in different hosts (local-to-or-from-remote, remoteA-remoteB).

> local sudo

In theory, everything works locally should work for in a local sudo connection, I'll make them available on next update if everything goes fine.

> Can rsync work in the second case given that root login is disabled on the remote host? ... multi-hop /ssh: to /sudo:

I'm not sure but I guess it would work because I found this https://github.com/stsquad/dired-rsync/blob/master/dired-rsync-ert.el#L58, I'll have a look on this.

> I don't know if it's possible, but it would be nice if dirvish could fall back to using TRAMP with synchronous copy/paste in cases that rsync can't handle or if things aren't configured correctly to allow rsync with ssh.

Good idea. I believe this can be done by the help of tramp and dired-aux.

**Comment by noctuid** [comment]
> As I described above, if the connection does not come with the direct-async-process property, every command takes ~ 1-2s (blocking) to establish the connection, then get spawned. Basically unusable

> So I disabled these features on synchronous connections (including mulit-hop ones), it won't block. You'll see "File preview is not supported in current TRAMP connection" in the preview window on this kind of connection.

I assume this was how long it took on a remote connection?  Did you test with a completely local multi-hop connection?  I bring this up because my usage of TRAMP has been mostly connecting to a local mini pc directly over an ethernet cable.  In this case, the connection might be much faster.  I don't know if it would be fast enough to allow preview to be usable (even a small synchronous delay would be annoying), so the current default behavior makes sense, but if it is a lot faster, it might make sense to let the user opt-in to some features for certain synchronous connections (e.g. local multihop sudo|docker or ssh|sudo for a local pc).  Missing preview is not a huge deal in these cases though.  I care more about copy/paste.

**Comment by alexluigit** [comment]
> I assume this was how long it took on a remote connection? 

Yes.

> Did you test with a completely local multi-hop connection? 

Nope, because I don't have an available local computer, please help me to test with the case C below. If everything goes fine, the expect behavior would be: 
A. connections w/o proper ssh config: defaults to `dired-copy/rename-file` (namely synchronous) 
B. connections w/ `direct-async-process` property: non-blocking
C. local connection (local multi-hop connections not tested): non-blocking

How does the preview and copy/paste work on paths like "/ssh:HOST_ON_ETHERNET|sudo:root@servername:/path/"? Not working at all? Performs bad? If it doesn't work, will adding HOST_ON_ETHERNET to `dirvish-whitelist-host-regex` do the trick?

**Comment by alexluigit** [comment]
> When I open Dirvish over a remote connection for which both users have rsync installed and have "direct-async-process" set to t, Emacs hangs indefinitely on the Dirvish buffer. 
@tdstoff , by 'hangs indefinitely' did you mean it hangs after invoking `dirvish-yank`?

**Comment by tdstoff** [comment]
> @tdstoff , by 'hangs indefinitely' did you mean it hangs after invoking `dirvish-yank`?

No, actually. I set the following:
```
  (add-to-list 'tramp-connection-properties
               (list (regexp-quote "/ssh:myuser@host:")
                     "direct-async-process" t))
```
and notice that file sizes are then shown like in this screenshot:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/43076118/182354680-ab32f7fb-b4cd-407c-a36b-36d6b6bd8d07.png">

But within ~10 seconds or so of using the buffer, I'm stuck in a hang that incessant `C-g`'s can't remedy. No use of `dirvish-yank` required to get this behavior.

**Comment by alexluigit** [comment]
See: https://github.com/alexluigit/dirvish/discussions/124

**Comment by Kabouik** [comment]
The issue is probably on my end, but I can yank files between remote and local machines using `dirvish-yank-menu` followed by `y` (`yank`, which uses `dired-copy-file`) but I get the following errors when trying to use `R` (`rsync`):

```
rsync finished @ Thu Jul 24 16:53:14 2025
ssh_askpass: exec(/gnu/store/8kman284vvlzk2hgy1bv1xzys3rfdzlr-openssh-10.0p1/libexec/ssh-askpass): No such file or directory
Permission denied, please try again.
ssh_askpass: exec(/gnu/store/8kman284vvlzk2hgy1bv1xzys3rfdzlr-openssh-10.0p1/libexec/ssh-askpass): No such file or directory
Received disconnect from ip_redacted port 22:2: Too many authentication failures
Disconnected from ip_redacted port 22
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(232) [Receiver=3.4.1]

```

This may be due to me using Guix system, where the file hierarchy is not standard (but symlinks should make it behave the same as standard). I've tried with several remote machines running different distributions and get the same issue; `rsync` is installed on all of them. My distribution has `*-ssh-askpass` packages but they are for X11, KDE or LXQT, and I use Wayland so I didn't install them. I did try the `x11-ssh-askpass` though but it didn't make a difference.

Note that I connect to them with TRAMP's `/sshx:` prefix because `/ssh:` would make it freeze due to unexpected `PS1` characters, [see this message(https://lists.gnu.org/archive/html/tramp-devel/2025-05/msg00005.html). Perhaps that's related (this is why I tried installing `x11-ssh-askpass`.

Not sure what `yank`/`dired-copy-file` use under the hood for remote/local transfers, `scp`?

By the way, I had `Dirvish` installed since years and never really got to learn it because I had no experience with `Dired` in the first place, and was more a `nnn` user, but I'm now discovering its capabilities and I'm loving it. It's awesome and I can't wait to annoy Windows colleagues by showing that to them even though they prefer `explorer.exe`.
