### ISSUE TITLE
Allow disabling or customizing listing colorization

### ISSUE THREAD

**Issue by chmouel** [alexluigit/dirvish#4]
It's nice to have colourization like diredfl but it would be nicer since this can be customized, on my setup/theme I find them a bit too much (ie: here the dates are not very readable) 

![image](https://user-images.githubusercontent.com/98980/147225991-1b3a378b-08b6-437f-b5a0-77731607ab13.png)

I am on emacs28/pgtk-native-comp and dired shows up like this for me : 

![image](https://user-images.githubusercontent.com/98980/147226430-207ed354-043c-40a8-9f47-d12e161fdc1c.png)

( i did try to disabled diredfl as well and dirvish still colour listing)

**Comment by alexluigit** [comment]
Hi @chmouel, thanks for your report.

The directory preview you see here is generated by `exa` (a shell command) and highlighted by `ansi-color.el`, which is a built-in package in Emacs.

If you want to customize some colors inside this preview window, I guess what you need is something like:

```emacs-lisp
;; I use white as an example, choose whatever color you want
(set-face-attribute 'ansi-color-blue nil :foreground "#FFFFFF") 
```
I get the face name described above by moving my cursor onto the target character and do `C-u M-x what-cursor-position`

Let me know if that helps.

**Comment by chmouel** [comment]
Thanks alex, 

ah interesting, yes i have exa installed, is there any way to be able to use the builtlin ls lisp or different "ls" ?

either way customizing ansi color sounds good to me, thank you,

**Comment by alexluigit** [comment]
There is no special reason to use `exa` here, it just happens I also use it in my shell. So yeah, you'll be able to customize directory preview cmd to any command you like, maybe `tree'. But for now it is `exa` is hard coded. I will update in this thread when this feature is ready, should not take too long. Stay tuned ;)

**Comment by chmouel** [comment]
thanks a lot! 🙇🏻 

(this probably would make things more portable too on platforms like Windows if they are able to use the lisp based ls)

**Comment by alexluigit** [comment]
Hi @chmouel , dirvish support customize preview for directory now (actually for any filetypes). It uses built-in dired  buffer for directory preview on Windows by default, since exa is not available on Windows (I haven't tested it yet). Have a look at `dirvish-preview-dispatchers' if you want further customization. I will improve the docs in the near future. Looking forward for your feedback, thanks!

**Comment by chmouel** [comment]
oh thank you so much, let me do an update and see how it works, thanks!

**Comment by chmouel** [comment]
i have just tested it with : 

```lisp
  (setq dirvish-preview-dispatchers
        (remove
         'dirvish-preview-directory-exa-dispatcher dirvish-preview-dispatchers))
```

and it works perfectly, loving it, thanks!

**Comment by alexluigit** [comment]
Great! Glad it works for you.
But I'm curious about how does directory preview looks on your machine. Are you on Windows? 
Because there are already following code in `dirvish.el` to setup directory preview for Windows.
```emacs-lisp
(when (memq system-type '(windows-nt ms-dos))
  (setq dirvish-preview-dispatchers
        (cl-substitute #'dirvish-preview-directory-dired-dispatcher
                       #'dirvish-preview-directory-exa-dispatcher
                       dirvish-preview-dispatchers)))
```
If everything works fine, it should replace the exa dispatcher with that dired one. 
So from my understanding, your `setq` should be redundant if the code above works fine on Windows (unless you really want to disable directory preview explicitly). 
Can you help me to confirm this? Paste your `dirvish-preview-dispatchers` and `system-type` here would be helpful, thanks!

**Comment by chmouel** [comment]
ah sorry I don't have Windows (I tested this on Linux), I was just suggesting for those users. 

yeah i am guessing from your code, my config would be not be needed on windows

**Comment by alexluigit** [comment]
Thanks for the confirm!
