### ISSUE TITLE
Symlink display issues

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#41]
The file size is not shown for me for symlinks when `dired-hide-details-hide-symlink-targets` is `t`.  If I change it to nil, I see the sizes.  I'm not sure if this is related to the symlink-target attribute.  I am not sure what the symlink-target attribute does.  It does not seem to have any effect for me (regardless of the value of `dired-hide-details-hide-symlink-targets`).

What I'd like is for an attribute and  amode line item that would allow symlink display to be like ranger: symlinks just show an arrow (instead of the full path on every line), and if the focused item is a symlink, the target path will be shown in the modeline.

**Comment by alexluigit** [comment]
This is actually a hack for the `dired-subtree` bug https://github.com/Fuco1/dired-hacks/issues/125. 
```emacs-lisp
;; Here is a quote from `dired-sidebar`
;; https://github.com/jojojames/dired-sidebar/issues/7
;; Symlinks are displayed incorrectly when these three things happen.
;; 1. `dired-hide-details-mode' is on.
;; 2. `dired-subtree' toggles a symlink folder via `dired-subtree-toggle'.
;; 3. `dired-hide-details-hide-symlink-targets' is set to true.

;; Since we use both 1 & 2, disable 3 to avoid the issue.
(setq-local dired-hide-details-hide-symlink-targets nil)
```

In other words, to make `dired-subtree` work correctly, the value of `dired-hide-details-hide-symlink-targets` has to be nil, which means we have to have the symlink target showing in the Dired/Dirvish buffer. In order to hide it (like it should), I created the `symlink-target` attribute in Dirvish.  The reason this attribute takes no effects on your side is that you also have `file-size` attribute, which "overrides" anything (except other dirvish attributes) after the end of filename.

> symlinks just show an arrow (instead of the full path on every line)

Personally, I think the coloring and icon (which is different from normal directory icon) are enough for me to identify a symlink visually, so I'm not sure this is a good idea to suffix a " -> " to the filename, but I'm open to discuss. If you want the arrow, I guess this should do the trick. But be sure to update first because this issue https://github.com/alexluigit/dirvish/issues/40 also relates to it.

```emacs-lisp
(dirvish-define-attribute symlink-target
  (:if (and dired-hide-details-mode
           (default-value 'dired-hide-details-hide-symlink-targets)))
  (when (< (+ f-end 4) l-end)
    (let ((ov (make-overlay (+ f-end 4) l-end)))
      (overlay-put ov 'invisible t) ov)))
```

> if the focused item is a symlink, the target path will be shown in the modeline.

Nice suggestion, done. By the way, Dirvish's header line can be customized the same way as the mode line, which means we have more freedom on how to place the segments.

See the default layout.

![2022-05-10_23-19](https://user-images.githubusercontent.com/16313743/167663850-9be29b57-cc79-424a-98dd-c7f78b616d3f.png)

**Comment by noctuid** [comment]
Thanks!

> file-size attribute, which "overrides" anything (except other dirvish attributes) after the end of filename.

Very minor since they are mostly self-explanatory, but it might be nice if `dirvish-define-attribute` allowed specifying a docstring for each attribute and programmatically appended these descriptions to the docstring for `dirvish--available-attrs`.

> Personally, I think the coloring and icon (which is different from normal directory icon) are enough for me to identify a symlink visually

This is fine for directories, but I have symlinked config files, for example, which don't get a different icon.  The example code works though.  Thanks.

> By the way, Dirvish's header line can be customized the same way as the mode line, which means we have more freedom on how to place the segments.

Thanks for the tip.  Things are getting kind of cramped.  In the examples in the readme it looks like the mode-line spans the left two panes.  Are these a single buffer or how does the header line span both panes?  Is it possible to do this now for the mode-line?  It might also be nice to be able to use the global mode line to be able span all 3 panes.

**Comment by alexluigit** [comment]
> it might be nice if `dirvish-define-attribute` allowed specifying a docstring for each attribute and programmatically appended these descriptions to the docstring for `dirvish--available-attrs`

Good idea. I've added `dirvish--available-mode-line-segments` as well.

> Things are getting kind of cramped. In the examples in the readme it looks like the mode-line spans the left two panes.

I disabled that for 2 reasons: 
1. To create a header/mode line across different panes, we have to split a window dedicated to it. I'm not sure it is a matter of Emacs configuration, but for some reason, this window has to have a minimal height of 2 (we can split the window with height of 1, the mode line won't show correctly in that window though). This is fine for header window, but the footer window causes issues with the `bottom-divider-width` frame-parameter (Screenshot from doom-emacs) 
![2022-05-11_17-05](https://user-images.githubusercontent.com/16313743/167813060-c58b9596-bee0-453d-a011-8be6c8602c5b.png)
and with some other packages such as `auto-dim-other-buffers-mode` which makes focused window has a different background color.

2. Usually, segments placed in the mode line shows the information (such as sorting criteria) only relevant to files in *root-window*'s `default-directory`. Although a cross-pane mode-line looks better in regards to symmetry, it may cause confusions because of the alignment. 

That said, I'm willing to provide a option to let people choose how to display to mode line, but until we solve the window minimal height issue, I'd like to keep the status quo as the default.

**Comment by alexluigit** [comment]
The new user option `dirvish-mode-line-position` introduced in 789a29e3b7289ac025da2e455d31edf4d1e812b1 allows us to customize the placement of mode line.

**Comment by noctuid** [comment]
> dirvish-mode-line-position

Great, thank you!  Maybe the documentation should mention the window minimal height issue.  I don't think it affects me, but I don't fully understand the screenshot.  Is the issue that the window with "d" is too small?  What is that window?
