### ISSUE TITLE
Optional posframe dependency

### ISSUE THREAD

**Issue by minad** [alexluigit/dirvish#5]
Hi,

I like the idea of your file manager - minimal, built on dired, preview etc! Would it be possible to avoid the posframe dependency or make it optional, such that dirvish only uses posframe if installed independently? It seems posframe is not crucial for dirvish? Thank you!

**Comment by alexluigit** [comment]
Hello @minad, I'm a happy user of your vertico and consult :) I'm glad you like this package, thanks!
In terms of posframe, I use it just for header window (more precisely, child-frame) generation, so yes, as you've pointed out, posframe can be avoided. But the problem is, without something like posframe, how do we deal the header? I know of ranger.el use header line for this, but as I mentioned in README, to concat header strings across multiple window is definitely not the way to go. Maybe get rid of header completely?  or just display one word in header for each window? Do you have any suggestions for it?

**Comment by minad** [comment]
Thanks! Yes, I would either get rid of the header completely, or show only a partial header in the header-line or create a separate sidebar window without modeline at the top. If none of these approaches is satisfactory it would be nice if the posframe is at least optional such that users can decide if they want posframe for the full-width header. From my perspective using a posframe for this purpose is a bit of a hack. I think child frames should ideally only be used for floating windows like Corfu, Company and maybe floating mini buffers (like mini-frame or vertico-posframe). But I tend to avoid child frames since they are not very robust from my experience. In my current setup I only use child frames for my Corfu package.

**Comment by alexluigit** [comment]
I have a similar feeling on child frame, besides it also have performance issues. 
I guess I will do add an option named `dirvish-header-type' to enable users to choose from 'big, 'small, nil, or something like that. I may implement it in the near future. Thanks for your suggestion!

**Comment by alexluigit** [comment]
Happy new year, @minad .
The posframe dependency has been removed now. 
I really wish I did this earlier. A regular window is obviously the best tool for this use case, I just didn't realize I can split a window with less than 4 lines height.
Now, not only all the windows are aligned perfectly, it also launches blazing fast!
Hope you can try out and let me know if you have any thoughts on this issue or on this project in general, thanks!

**Comment by minad** [comment]
Great work! Happy new year!
