### ISSUE TITLE
Question Regarding Clocking Out Of Tasks

### ISSUE THREAD

**Issue by SamuelBanya** [alexluigit/dirvish#52]
Hey there,

I like your project a ton. The only issue I'm having is that if I launch 'dirvish' from an Org Mode buffer containing a clocked-in task, Dirvish asks me if I want to clock out of the task itself.

Is there any way I can prevent this action from occurring? I ask because I am finding this to be hindering since I use Org mode based todolists for work all of the time with clock in tasks, so I would love to know how to not allow Dirvish to interfere with this.

Thanks,

Sam

**Comment by alexluigit** [comment]
Hey Sam, thanks for reporting. I guess this is not a Dirvish issue because it does not require `org` nor impact `org-mode`'s behavior in any way, meanwhile I'm not being able to reproduce this in `emacs -q`. What does the clock-out prompt say? What's the steps and minimal config to reproduce this?

**Comment by SamuelBanya** [comment]
Actually, this is the more specific ways to reproduce it:
I clock into a task for my work todo list.

I then launch 'M-x dirvish'.

I then get a prompt window from Emacs on MacOS stating:
"Clock-out in buffer TodoList(2022).org before killing it?"

That's all that I did.

**Comment by alexluigit** [comment]
Both the "Clock-out in buffer TodoList(2022).org before killing it?" and "Buffer TodoList(2022).org modified; kill anyway?" prompt are invoked before a buffer is going to be killed, but Dirvish does not kill any buffer during the session initialization, so theoretically this prompt is not invoked by Dirvish, in other words, I believe this prompt is brought by other packages reside in your _configuration.org_. As I said, I can not reproduce this with the following steps after launching Emacs with `emacs -q -L dirvish -l dirvish`

``` 
1. Open a sample org file "Todo.org".
2. M-x `org-clock-in`
3. M-x `dirvish`
```
No prompt shows up for me.

I'll look into this if you can confirm this prompt is raised by Dirvish rather than other packages (by providing  a reproducible `emacs -q` recipe) or if we receive similar reports from other users, thanks.

**Comment by SamuelBanya** [comment]
The only thing I can think of personally is that I personally have a function that literally only keeps one Dired buffer open at a time to prevent duplicate Dired buffers from existing.

I'm assuming Dirvish is based upon Dired itself?

If not, that's fine, probably just a config issue like you said.

Here's that line of my config to nuke Dired alternate buffers:

#+BEGIN_SRC emacs-lisp
  ;; Taken From Xah Lee's Site:
  ;; http://ergoemacs.org/emacs/emacs_dired_tips.html

  ;; Also taken from this SO post:
  ;; https://stackoverflow.com/questions/1839313/how-do-i-stop-emacs-dired-mode-from-opening-so-many-buffers

  ;; Make a wrapper function to force dired-mode to load first:
  (with-eval-after-load 'dired
    ;; Disable annoying warning to utilize 'dired-find-alternate-file' function:
    (put 'dired-find-alternate-file 'disabled nil)

    ;; Nuke 'dired' mode's ability to unnecessarily create so many buffers with the sane 'ENTER' key press:
    (define-key dired-mode-map (kbd "RET") 'dired-find-alternate-file)

    ;; Do the same action, but for the '^' key as well since the same issue of creating too many buffers exists
    ;; for the '^' key by default
    (define-key dired-mode-map (kbd "^")
      (lambda () (interactive)
(find-alternate-file ".."))))
#+END_SRC

On Wed, Jun 1, 2022, at 12:36 AM, Alex Lu wrote:
> 
> 
> Both the "Clock-out in buffer TodoList(2022).org before killing it?" and "Buffer TodoList(2022).org modified; kill anyway?" prompt are invoked before a buffer is going to be killed, but Dirvish does not kill any buffer during the session initialization, so theoretically this prompt is not invoked by Dirvish, in other words, I believe this prompt is brought by other packages reside in your *configuration.org*. As I said, I can not reproduce this with the following steps after launching Emacs with `emacs -q -L dirvish -l dirvish`
> 
> `1. Open a sample org file "Todo.org".
> 2. M-x `org-clock-in`
> 3. M-x `dirvish`
`

**Comment by alexluigit** [comment]
The config you mentioned here won't cause this issue, although they are unnecessary for Dirvish (Dirvish clean its buffers automatically, see the [FAQ.org](https://github.com/alexluigit/dirvish/blob/main/FAQ.org#how-is-dirvish-related-to-dired)).  IMHO the best way to locate the cause of the problem is to bisect your Emacs config (from `emacs -q`), otherwise it would very difficult to find out the cause by just guessing.
