### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by chmouel** [alexluigit/dirvish#6]
Hello,

Thanks again alex for this wonderful mode,

I think (or maybe I am not using it correctly) dirvish is not playing well with multiple 'instance'

I often use multiple emacs tabs.

I start opening dirvish in the current tab and leave it there.

when I open a new tab with new dirvish browser and then if I quit that new dirvish, the old ones would quit as well and would show the 3 columuns but with no dirvish buffers.

let me know if that make sense, or if not I can make a bit more visual bug report with screenshots to explain what i mean.

**Comment by alexluigit** [comment]
Thanks for reporting this, Chmouel. I guess I knew the situation you encountered.
Please help me to identify the issue with following steps:
- Open a new tab, call it tab2 
- Open dirvish2 in tab2 
- Switch back to tab1
- Open dirvish1 in tab1
- Quit dirvish1
- Switch to tab2
Will dirvish2 get killed?
I'm trying to figure out if this issue only happens when you open a new tab while focusing a dirvish instance. Thanks

**Comment by alexluigit** [comment]
Either way, see if the latest commit solves the problem.

**Comment by chmouel** [comment]
@alexluigit yep exactly, thanks for the quick fix, it works exactly as intended, when I quit another dirvish buffer, it doesn't kill the other dirvish buffers, thanks!
