### ISSUE TITLE
Dirvish-Dispatch returns: "transient-setup: Symbol’s value as variable is void: desc-len"

### ISSUE THREAD

**Issue by Jay-Quellin** [alexluigit/dirvish#75]
I have just started using dirvish, and so far it looks amazing! The only thing that I couldn't figure out is that when I call dirvish-dispatch I only get the following message: 

transient-setup: Symbol’s value as variable is void: desc-len

What could be causing this? It seems to work with an empty init.el, and I cannot figure out what causes the interference in my configuration. For dirvish, I am using the sample config from the customizing section.

Thanks a lot!

**Comment by Jay-Quellin** [comment]
Yes, I pulled it from Melpa yesterday, package.el prints the version number 20220711.820. I'm using  Emacs 28.1, if that is of any help.

**Comment by Jay-Quellin** [comment]
Sadly, this hasn't fixed it, but thanks anyway for the quick response! Did you just hardcode some bookmark entries with the commit, so that the when-let* statement in the dirvish-bookmark-entries would always return true? Sadly, my elisp is still too basic to decipher what that when-let* statement does. In any case,  I will investigate my own configuration some more tomorrow, hopefully something turns up!

**Comment by Jay-Quellin** [comment]
I have been playing around with my config a bit more, and found out that dirvish dispatch works fine when as long as dirvish-bookmark-entries is set to nil. Furthermore, it will also work if I manually evaluate the defcustom block in dirvish-bookmark.el. It does not seem like it is connected to my use-package configuration for dirvish, even the most basic configuration results in this error.

**Comment by alexluigit** [comment]
I have no idea why this happened.  If you can eval this block without issue, then it should not cause errors on startup.  Maybe you should clean up the .elc/.eln files of dirvish and try to rebuild the package.

> It does not seem like it is connected to my use-package configuration for dirvish

You can post the minimal configuration to reproduce this issue here, that would be helpful for me to diagnose.

**Comment by Jay-Quellin** [comment]
Yes, I can't make sense of that either. I just put the defcustom block into my init.el to cause it to be evaluated on startup, which seems to work for now. I tried just pulling the package without any configuration like so:

    (use-package dirvish
      :straight t)

As said before when using dirvish in an empty emacs-config, it worked for me as well, so some other package must cause the interference. So far I couldn't figure out which one, if you would like to dissect it you can find it at https://gitlab.com/MuellerF/emacs.

In any case, thank you very much for the work you put into dirvish, it's an awesome package!

**Comment by Jay-Quellin** [comment]
Awesome, that fixed it indeed! Would you mind sharing how requiring this library solved the issue? I couldn't figure it out from looking at the code, and I couldn't find any documentation.

**Comment by alexluigit** [comment]
I glanced through your init.el and didn't notice anything that could lead to this error.  You also mentioned that the error occurred even with minimal config.  These two things together made me believe that the problem might be caused by the Emacs itself, namely the major version or something. So I checked the source code of that library and realized that the `when-let*` macro was defined in `subr-x`, whereas now it is defined in `subr`.  That explains why I didn't experience the same issue on Emacs 29.  I think the tricky part is that the _void variable_ error message is a little bit misleading, something like "when-let* is not defined" would be more helpful.
